name: test

on:
  workflow_dispatch:

jobs:
  test-workflow:
    name: Test Workflow
    runs-on: windows-latest
    steps:
      - name: Display the path
        run: echo ${env:PATH}
        shell: powershell
      - name: Check out code
        uses: actions/checkout@v1
      # - name: Config credentials
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
      #   shell: powershell
      #   run: |
      #     git config --global pull.rebase true
      #     git config --global url."https://dvonthenen:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
      #     git config user.name dvonthenen
      #     git config user.email davidvonthenen@gmail.com
      - name: Build
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        run: |
          git config --global credential.https://github.com.helper ''
          git config --global 'credential.https://github.com' '!gh auth git-credential'
          git config --global credential.helper store
          Set-Content -Path "$HOME\.git-credentials" -Value "https://$GH_TOKEN:x-oauth-basic@github.com`n" -NoNewline
          git config user.name dvonthenen
          git config user.email davidvonthenen@gmail.com
          gh auth login
          git checkout main
          git reset --hard
          git checkout -b mytest
          "test" | Out-File -FilePath test.txt
          git add -A
          git commit -s -m "test"
          git push origin mytest
          gh pr create --title "auto-generated - test" --body "auto-generated - test" --base "main"
          gh pr merge "automation-test" --delete-branch --squash --admin
